name: precompile-openbsd

on:
  workflow_dispatch:
    inputs:
      otp_version:
        required: true
      build_x86_64:
        description: 'Build x86_64'
        required: false
        default: true
        type: boolean
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.otp_version }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  openbsd:
    runs-on: ubuntu-latest
    env:
      OPENSSL_VERSION: "3.6.3"
      OPENSSL_VERSION_OTP_24_AND_BELOW: "1.1.1w"
    strategy:
      matrix:
        job:
          - { major: "7", minor: "7" }
      fail-fast: false

    name: x86_64-unknown-openbsd

    steps:
      - name: Build Check
        id: build-check
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "build=true" >> $GITHUB_OUTPUT
            export BUILD_VERSION_V="v${GITHUB_REF##*/v}"
          else
            echo "build=${{ inputs.build_x86_64 }}" >> $GITHUB_OUTPUT
            export BUILD_VERSION_V="${{ inputs.otp_version }}"
          fi

          export BUILD_VERSION="${BUILD_VERSION_V#v}"
          echo "version=${BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Checkout
        if: steps.build-check.outputs.build == 'true'
        uses: actions/checkout@v6

      - name: Cache Precompiled OpenSSL for OTP 24 and below
        if: steps.build-check.outputs.build == 'true' && (startsWith(steps.build-check.outputs.version, '24.') || startsWith(steps.build-check.outputs.version, '23.'))
        id: cache-openssl-otp24
        uses: actions/cache@v5
        with:
          key: openssl-111-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-openbsd${{ matrix.job.major }}.${{ matrix.job.minor }}
          path: |
            ./openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-openbsd.tar.gz

      - name: Download Precompiled OpenSSL for OTP 24 and below
        if: steps.build-check.outputs.build == 'true' && (startsWith(steps.build-check.outputs.version, '24.') || startsWith(steps.build-check.outputs.version, '23.')) && steps.cache-openssl-otp24.outputs.cache-hit != 'true'
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION_OTP_24_AND_BELOW}/openssl-x86_64-unknown-openbsd.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-openbsd.tar.gz"

      - name: Cache Precompiled OpenSSL for OTP 25 and above
        if: "steps.build-check.outputs.build == 'true' && !startsWith(steps.build-check.outputs.version, '24.') && !startsWith(steps.build-check.outputs.version, '23.')"
        id: cache-openssl
        uses: actions/cache@v5
        with:
          key: openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-openbsd${{ matrix.job.major }}.${{ matrix.job.minor }}
          path: |
            ./openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-openbsd.tar.gz

      - name: Download Precompiled OpenSSL for OTP 25 and above
        if: "steps.build-check.outputs.build == 'true' && !startsWith(steps.build-check.outputs.version, '24.') && !startsWith(steps.build-check.outputs.version, '23.') && steps.cache-openssl.outputs.cache-hit != 'true'"
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION}/openssl-x86_64-unknown-openbsd.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-openbsd.tar.gz"

      - name: Cache OTP Source Code
        if: steps.build-check.outputs.build == 'true'
        id: cache-otp
        uses: actions/cache@v5
        with:
          key: otp-${{ steps.build-check.outputs.version }}
          path: |
            ./otp_src_${{ steps.build-check.outputs.version }}.tar.gz

      - name: Download OTP Source Code
        if: steps.build-check.outputs.build == 'true' && steps.cache-otp.outputs.cache-hit != 'true'
        run: |
          export OTP_VERSION=${{ steps.build-check.outputs.version }}
          curl -fSL "https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz" || \
          curl -fSL "https://github.com/erlang/otp/archive/refs/tags/OTP-${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz"

      - name: Compile in OpenBSD
        if: steps.build-check.outputs.build == 'true'
        id: compile-openbsd
        uses: vmactions/openbsd-vm@v1
        with:
          envs: "OPENSSL_VERSION OPENSSL_VERSION_OTP_24_AND_BELOW"
          release: ${{ matrix.job.major }}.${{ matrix.job.minor }}
          usesh: true
          sync: rsync
          prepare: |
            pkg_add curl gmake gtar--

          run: |
            export TRIPLET=x86_64-unknown-openbsd
            export ROOT_DIR="$(pwd)"
            echo "ROOT_DIR: $ROOT_DIR"
            export OTP_VERSION=${{ steps.build-check.outputs.version }}

            case "${OTP_VERSION}" in
              24.* | 23.*)
                export OPENSSL_PERFIX_DIR=/tmp/openssl-${OPENSSL_VERSION_OTP_24_AND_BELOW}-${TRIPLET}
                export OPENSSL_ARCHIVE="openssl-${OPENSSL_VERSION_OTP_24_AND_BELOW}-${TRIPLET}.tar.gz"
                ;;
              *)
                export OPENSSL_PERFIX_DIR=/openssl-${OPENSSL_VERSION}-${TRIPLET}
                export OPENSSL_ARCHIVE="openssl-${OPENSSL_VERSION}-${TRIPLET}.tar.gz"
                ;;
            esac

            mkdir -p "${OPENSSL_PERFIX_DIR}"
            tar xzf "${OPENSSL_ARCHIVE}" -C "${OPENSSL_PERFIX_DIR}"
            rm -rf "otp_src_${OTP_VERSION}"
            mkdir -p "otp_src_${OTP_VERSION}"
            gtar xzf "otp_src_${OTP_VERSION}.tar.gz" -C "otp_src_${OTP_VERSION}" --strip-components=1
            rm -f "otp_src_${OTP_VERSION}.tar.gz"
            cd "otp_src_${OTP_VERSION}"

            export DESTDIR="${ROOT_DIR}/otp_src_${OTP_VERSION}/otp_${OTP_VERSION}"

            ./configure --without-javac --with-ssl="${OPENSSL_PERFIX_DIR}" --disable-dynamic-ssl-lib
            gmake -j$(getconf NPROCESSORS_ONLN)
            echo "Install OTP to otp_${OTP_VERSION}"
            gmake DESTDIR="${DESTDIR}" install
            echo "Create tarball at ${ROOT_DIR}/otp-${TRIPLET}.tar.gz"
            cd "${DESTDIR}"
            gtar -czf "${ROOT_DIR}/otp-${TRIPLET}.tar.gz" .
            cd ..
            rm -rf "otp_${OTP_VERSION}"
            cd "${ROOT_DIR}"
            rm -rf "otp_src_${OTP_VERSION}"
            rm -f "${OPENSSL_ARCHIVE}"
            ls -lah "${ROOT_DIR}"

      - name: check outputs
        if: steps.build-check.outputs.build == 'true'
        id: check-outputs
        run: |
          export TRIPLET=x86_64-unknown-openbsd
          if [ ! -f "otp-${TRIPLET}.tar.gz" ]; then
            echo "has_tarball=false" >> $GITHUB_OUTPUT
          else
            echo "has_tarball=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup tmate session
        if: steps.build-check.outputs.build == 'true' && steps.check-outputs.outputs.has_tarball == 'false'
        uses: mxschmitt/action-tmate@v3

      - uses: softprops/action-gh-release@v3
        if: steps.build-check.outputs.build == 'true'
        with:
          tag_name: v${{ steps.build-check.outputs.version }}
          name: v${{ steps.build-check.outputs.version }}
          files: |
            otp-*.tar.gz

      - name: Check tarball again
        if: steps.build-check.outputs.build == 'true'
        run: |
          ls -lah
