name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  macos:
    runs-on: macos-12
    strategy:
      matrix:
        arch: [x86_64, arm64]
    name: ${{ matrix.arch }}-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - name: Download OTP Source Code
        run: |
          export OTP_VERSION=${GITHUB_REF##*/v}
          echo "$OTP_VERSION"
          curl -fSL "https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz"
          tar -xzf "otp_src_${OTP_VERSION}.tar.gz"
          cd "otp_src_${OTP_VERSION}"
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            export CC="clang -arch arm64"
            export CXX="clang -arch arm64"
            export CFLAGS="-arch arm64 -O2 -g"
            export CXXFLAGS="-arch arm64 -O2 -g"
            export LDFLAGS="-arch arm64"
            ./configure --host=aarch64-apple-darwin
          else
            ./configure
          fi
          time make -j"$(sysctl -n hw.ncpu)"
          mkdir "otp_${OTP_VERSION}"
          make DESTDIR="$(pwd)/otp_${OTP_VERSION}" install
          mkdir -p build
          tar -czf "build/otp_${OTP_VERSION}.tar.gz" otp_${OTP_VERSION}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.tar.gz
