name: precompile-arm64-apple-darwin

on:
  push:
    tags:
      - "v24.3*"
      - "v25*"
      - "v26*"
      - "v27*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  arm64-apple-darwin:
    runs-on: macos-12
    env:
      OPENSSL_VERSION: "3.2.1"
      OPENSSL_VERSION_OTP_24_AND_BELOW: "1.1.1w"

    name: arm64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Precompiled OpenSSL for OTP 24 (24.3+)
        if: startsWith(github.ref, 'refs/tags/v24')
        id: cache-openssl-otp24
        uses: actions/cache@v4
        with:
          key: openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-arm64-apple-darwin
          path: |
            ./openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-arm64-apple-darwin.tar.gz

      - name: Download Precompiled OpenSSL for OTP 24 (24.3+)
        if: startsWith(github.ref, 'refs/tags/v24') && steps.cache-openssl-otp24.outputs.cache-hit != 'true'
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION_OTP_24_AND_BELOW}/openssl-arm64-apple-darwin.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-arm64-apple-darwin.tar.gz"

      - name: Cache Precompiled OpenSSL
        if: startsWith(github.ref, 'refs/tags/v24') != 'true'
        id: cache-openssl
        uses: actions/cache@v4
        with:
          key: openssl-${{ env.OPENSSL_VERSION }}-arm64-apple-darwin
          path: |
            ./openssl-${{ env.OPENSSL_VERSION }}-arm64-apple-darwin.tar.gz

      - name: Download Precompiled OpenSSL
        if: startsWith(github.ref, 'refs/tags/v24') != 'true' && steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION}/openssl-arm64-apple-darwin.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION }}-arm64-apple-darwin.tar.gz"

      - name: Cache OTP Source Code
        id: cache-otp
        uses: actions/cache@v4
        with:
          key: otp-${{ github.ref_name }}
          path: |
            ./otp_src_${{ github.ref_name }}.tar.gz

      - name: Download OTP Source Code
        if: steps.cache-otp.outputs.cache-hit != 'true'
        run: |
          export OTP_VERSION=${GITHUB_REF##*/v}
          echo "OTP_VERSION: $OTP_VERSION"
          echo "github.ref_name: ${{ github.ref_name }}"
          curl -fSL "https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" -o "otp_src_${{ github.ref_name }}.tar.gz" || \
          curl -fSL "https://github.com/erlang/otp/archive/refs/tags/OTP-${OTP_VERSION}.tar.gz" -o "otp_src_${{ github.ref_name }}.tar.gz"

      - name: Compile OTP
        run: |
          export ROOTDIR="$(pwd)"

          case "${{ github.ref_name }}" in
            v24.*)
              export OPENSSL_ARCHIVE="openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-arm64-apple-darwin.tar.gz"
              export PERFIX_DIR="/tmp/openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-arm64-apple-darwin"
              ;;
            *)
              export OPENSSL_ARCHIVE="openssl-${{ env.OPENSSL_VERSION }}-arm64-apple-darwin.tar.gz"
              export PERFIX_DIR="/tmp/openssl-${{ env.OPENSSL_VERSION }}-arm64-apple-darwin"
              ;;
          esac

          export OTP_VERSION="${GITHUB_REF##*/v}"
          mkdir -p "${PERFIX_DIR}"
          sudo tar -C "${PERFIX_DIR}" -xf "${OPENSSL_ARCHIVE}"
          tar -xzf "otp_src_${{ github.ref_name }}.tar.gz"
          cd "otp_src_${OTP_VERSION}"
          mkdir "otp_${OTP_VERSION}"
          ./otp_build configure --xcomp-conf=xcomp/erl-xcomp-aarch64-darwin.conf --without-javac --with-ssl="${PERFIX_DIR}" --disable-dynamic-ssl-lib
          ./otp_build boot -a
          make DESTDIR="$(pwd)/otp_${OTP_VERSION}" install
          mkdir -p "${ROOTDIR}/build"
          cd "$(pwd)/otp_${OTP_VERSION}"
          tar -czf "${ROOTDIR}/build/otp-arm64-apple-darwin.tar.gz" .

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.tar.gz

  deploy-arm64-apple-darwin:
    runs-on: ubuntu-latest
    needs: arm64-apple-darwin
    steps:
      - name: deploy
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'cocoa-xu/otp-build'
        env:
          DEPLOY_ARM64_MACOS_HOOK_URL: ${{ secrets.DEPLOY_ARM64_MACOS_HOOK_URL }}
        run: |
          curl -sS --no-progress-meter "${DEPLOY_ARM64_MACOS_HOOK_URL}${{ github.ref_name }}"
