name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  macos:
    runs-on: macos-12
    strategy:
      matrix:
        arch: [x86_64, arm64]
    name: ${{ matrix.arch }}-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - name: Download OTP Source Code
        run: |
          export OTP_VERSION=${GITHUB_REF##*/v}
          echo "$OTP_VERSION"
          curl -fSL "https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz"
          tar -xzf "otp_src_${OTP_VERSION}.tar.gz"
          cd "otp_src_${OTP_VERSION}"
          mkdir "otp_${OTP_VERSION}"
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            ./otp_build configure --xcomp-conf=xcomp/erl-xcomp-aarch64-darwin.conf
            ./otp_build boot -a
            
            ./otp_build release -a "otp_${OTP_VERSION}"
          else
            ./configure
            time make -j"$(sysctl -n hw.ncpu)"
            make DESTDIR="$(pwd)/otp_${OTP_VERSION}" install
          fi
          mkdir -p build
          tar -czf "build/otp_${OTP_VERSION}.tar.gz" otp_${OTP_VERSION}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.tar.gz
