name: precompile-netbsd

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  netbsd:
    runs-on: ubuntu-latest
    env:
      OPENSSL_VERSION: "3.2.1"
      OPENSSL_VERSION_OTP_24_AND_BELOW: "1.1.1w"
    strategy:
      matrix:
        include:
          - pair:
              fullversion: "9.0"
              major: "9"
        # - pair:
        #     fullversion: "9.1"
        #     major: "9"
        # - pair:
        #     fullversion: "9.2"
        #     major: "9"
        # - pair:
        #     fullversion: "9.3"
        #     major: "9"
      fail-fast: false

    name: x86_64-unknown-netbsd${{ matrix.pair.fullversion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Precompiled OpenSSL for OTP 24 and below
        if: startsWith(github.ref, 'refs/tags/v24') || startsWith(github.ref, 'refs/tags/v23')
        id: cache-openssl-otp24
        uses: actions/cache@v4
        with:
          key: openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-netbsd${{ matrix.pair.major }}
          path: |
            ./openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-netbsd${{ matrix.pair.major }}.tar.gz

      - name: Download Precompiled OpenSSL for OTP 24 and below
        if: steps.cache-openssl-otp24.outputs.cache-hit != 'true'
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION_OTP_24_AND_BELOW}/openssl-x86_64-unknown-netbsd${{ matrix.pair.major }}.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-netbsd${{ matrix.pair.major }}.tar.gz"

      - name: Cache Precompiled OpenSSL
        if: "!startsWith(github.ref, 'refs/tags/v24') && !startsWith(github.ref, 'refs/tags/v23')"
        id: cache-openssl
        uses: actions/cache@v4
        with:
          key: openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-netbsd${{ matrix.pair.major }}
          path: |
            ./openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-netbsd${{ matrix.pair.major }}.tar.gz

      - name: Download Precompiled OpenSSL
        if: "!startsWith(github.ref, 'refs/tags/v24') && !startsWith(github.ref, 'refs/tags/v23') && steps.cache-openssl.outputs.cache-hit != 'true'"
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION}/openssl-x86_64-unknown-netbsd${{ matrix.pair.major }}.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-netbsd${{ matrix.pair.major }}.tar.gz"

      - name: Cache OTP Source Code
        id: cache-otp
        uses: actions/cache@v4
        with:
          key: otp-${{ github.ref_name }}
          path: |
            ./otp_src_${{ github.ref_name }}.tar.gz

      - name: Download OTP Source Code
        if: steps.cache-otp.outputs.cache-hit != 'true'
        run: |
          export OTP_VERSION=${GITHUB_REF##*/v}
          echo "OTP_VERSION: $OTP_VERSION"
          echo "github.ref_name: ${{ github.ref_name }}"
          curl -fSL "https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" -o "otp_src_${{ github.ref_name }}.tar.gz"

      - name: Compile in NetBSD
        id: compile-netbsd
        uses: vmactions/netbsd-vm@v1
        with:
          envs: "OPENSSL_VERSION OPENSSL_VERSION_OTP_24_AND_BELOW"
          release: ${{ matrix.pair.fullversion }}
          usesh: true
          prepare: |
            /usr/sbin/pkg_add curl gmake perl

          run: |
            export TRIPLET=x86_64-unknown-netbsd${{ matrix.pair.major }}
            export OTP_VERSION="${GITHUB_REF##*/v}"
            export ROOT_DIR="$(pwd)"

            case "${{ github.ref_name }}" in
              v24.* | v23.*)
                export OPENSSL_PERFIX_DIR=/openssl-${OPENSSL_VERSION_OTP_24_AND_BELOW}-${TRIPLET}
                export OPENSSL_ARCHIVE="openssl-${OPENSSL_VERSION_OTP_24_AND_BELOW}-${TRIPLET}.tar.gz"
                ;;
              *)
                export OPENSSL_PERFIX_DIR=/openssl-${OPENSSL_VERSION}-${TRIPLET}
                export OPENSSL_ARCHIVE="openssl-${OPENSSL_VERSION}-${TRIPLET}.tar.gz"
                ;;
            esac

            mkdir -p "${OPENSSL_PERFIX_DIR}"
            tar -C "${OPENSSL_PERFIX_DIR}" -xzf "${OPENSSL_ARCHIVE}"
            tar -xzf "otp_src_${GITHUB_REF_NAME}.tar.gz"
            cd "otp_src_${OTP_VERSION}"
            ./configure --without-javac --with-ssl="${OPENSSL_PERFIX_DIR}" --disable-dynamic-ssl-lib
            gmake -j$(getconf NPROCESSORS_ONLN)
            gmake DESTDIR="$(pwd)/otp_${OTP_VERSION}" install
            cd "otp_${OTP_VERSION}"
            tar -czf "${ROOT_DIR}/otp-${TRIPLET}.tar.gz" .

            cd "${ROOT_DIR}"
            rm -rf "otp_src_${OTP_VERSION}" "otp_${OTP_VERSION}" "${OPENSSL_PERFIX_DIR}"

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            otp-*.tar.gz

  deploy-netbsd:
    runs-on: ubuntu-latest
    needs: netbsd
    steps:
      - name: deploy
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'cocoa-xu/otp-build'
        env:
          DEPLOY_NETBSD9_HOOK_URL: ${{ secrets.DEPLOY_NETBSD9_HOOK_URL }}
        run: |
          curl -sS --no-progress-meter "${DEPLOY_NETBSD9_HOOK_URL}${{ github.ref_name }}"
