name: precompile-netbsd

on:
  workflow_dispatch:
    inputs:
      otp_version:
        required: true
      build_x86_64:
        description: 'Build x86_64'
        required: false
        default: true
        type: boolean
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.otp_version }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  netbsd:
    runs-on: ubuntu-latest
    env:
      OPENSSL_VERSION: "3.6.3"
      OPENSSL_VERSION_OTP_24_AND_BELOW: "1.1.1w"
    strategy:
      matrix:
        job:
          - { fullversion: "9.0", major: "9" }
      fail-fast: false

    name: x86_64-unknown-netbsd

    steps:
      - name: Build Check
        id: build-check
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "build=true" >> $GITHUB_OUTPUT
            export BUILD_VERSION_V="v${GITHUB_REF##*/v}"
          else
            echo "build=${{ inputs.build_x86_64 }}" >> $GITHUB_OUTPUT
            export BUILD_VERSION_V="${{ inputs.otp_version }}"
          fi

          export BUILD_VERSION="${BUILD_VERSION_V#v}"
          echo "version=${BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Checkout
        if: steps.build-check.outputs.build == 'true'
        uses: actions/checkout@v6

      - name: Cache Precompiled OpenSSL for OTP 24 and below
        if: steps.build-check.outputs.build == 'true' && (startsWith(steps.build-check.outputs.version, '24.') || startsWith(steps.build-check.outputs.version, '23.'))
        id: cache-openssl-otp24
        uses: actions/cache@v5
        with:
          key: openssl-111-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-netbsd${{ matrix.job.fullversion }}
          path: |
            ./openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-netbsd.tar.gz

      - name: Download Precompiled OpenSSL for OTP 24 and below
        if: steps.build-check.outputs.build == 'true' && (startsWith(steps.build-check.outputs.version, '24.') || startsWith(steps.build-check.outputs.version, '23.')) && steps.cache-openssl-otp24.outputs.cache-hit != 'true'
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION_OTP_24_AND_BELOW}/openssl-x86_64-unknown-netbsd.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION_OTP_24_AND_BELOW }}-x86_64-unknown-netbsd.tar.gz"

      - name: Cache Precompiled OpenSSL for OTP 25 and above
        if: "steps.build-check.outputs.build == 'true' && !startsWith(steps.build-check.outputs.version, '24.') && !startsWith(steps.build-check.outputs.version, '23.')"
        id: cache-openssl
        uses: actions/cache@v5
        with:
          key: openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-netbsd${{ matrix.job.fullversion }}
          path: |
            ./openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-netbsd.tar.gz

      - name: Download Precompiled OpenSSL for OTP 25 and above
        if: "steps.build-check.outputs.build == 'true' && !startsWith(steps.build-check.outputs.version, '24.') && !startsWith(steps.build-check.outputs.version, '23.') && steps.cache-openssl.outputs.cache-hit != 'true'"
        run: |
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${OPENSSL_VERSION}/openssl-x86_64-unknown-netbsd.tar.gz" -o "openssl-${{ env.OPENSSL_VERSION }}-x86_64-unknown-netbsd.tar.gz"

      - name: Cache OTP Source Code
        if: steps.build-check.outputs.build == 'true'
        id: cache-otp
        uses: actions/cache@v5
        with:
          key: otp-${{ steps.build-check.outputs.version }}
          path: |
            ./otp_src_${{ steps.build-check.outputs.version }}.tar.gz

      - name: Download OTP Source Code
        if: steps.build-check.outputs.build == 'true' && steps.cache-otp.outputs.cache-hit != 'true'
        run: |
          export OTP_VERSION=${{ steps.build-check.outputs.version }}
          curl -fSL "https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz" || \
          curl -fSL "https://github.com/erlang/otp/archive/refs/tags/OTP-${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz"

      - name: Compile in NetBSD
        if: steps.build-check.outputs.build == 'true'
        id: compile-netbsd
        uses: vmactions/netbsd-vm@v1
        with:
          envs: "OPENSSL_VERSION OPENSSL_VERSION_OTP_24_AND_BELOW"
          release: ${{ matrix.job.fullversion }}
          usesh: true
          prepare: |
            /usr/sbin/pkg_add curl gmake perl

          run: |
            export TRIPLET=x86_64-unknown-netbsd
            sh ./.github/build-bsd.sh netbsd "${TRIPLET}" "${{ steps.build-check.outputs.version }}"

      - uses: softprops/action-gh-release@v3
        if: steps.build-check.outputs.build == 'true'
        with:
          tag_name: v${{ steps.build-check.outputs.version }}
          name: v${{ steps.build-check.outputs.version }}
          files: |
            otp-*.tar.gz
