name: precompile-linux-musl

on:
  workflow_dispatch:
    inputs:
      otp_version:
        description: 'OTP Version (X.Y.Z)'
        required: true
      openssl:
        description: 'use OpenSSL'
        required: false
        default: 'static'
        type: choice
        options:
          - static
          - shared
      build_x86_64:
        description: 'Build x86_64'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
      build_i386:
        description: 'Build i386'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
      build_ppc64le:
        description: 'Build ppc64le'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
      build_s390x:
        description: 'Build s390x'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.otp_version }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  linux-musl:
    runs-on: ubuntu-latest
    env:
      DEFAULT_OPENSSL_VERSION: "3.5.0"
      DEFAULT_OPENSSL_VERSION_OTP24: "1.1.1w"
    strategy:
      matrix:
        arch: [x86_64, i386, ppc64le, s390x]
      fail-fast: false

    name: ${{ matrix.arch }}-linux-musl

    steps:
      - name: Build Check
        id: build-check
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "build=true" >> $GITHUB_OUTPUT
            export OTP_VERSION_V=${GITHUB_REF##*/v}
            echo "with_openssl=static" >> $GITHUB_OUTPUT
          else
            if [ "${{ matrix.arch }}" == "x86_64" ]; then
              echo "build=${{ inputs.build_x86_64 }}" >> $GITHUB_OUTPUT
            fi

            if [ "${{ matrix.arch }}" == "i386" ]; then
              echo "build=${{ inputs.build_i386 }}" >> $GITHUB_OUTPUT
            fi

            if [ "${{ matrix.arch }}" == "ppc64le" ]; then
              echo "build=${{ inputs.build_ppc64le }}" >> $GITHUB_OUTPUT
            fi

            if [ "${{ matrix.arch }}" == "s390x" ]; then
              echo "build=${{ inputs.build_s390x }}" >> $GITHUB_OUTPUT
            fi

            export OTP_VERSION_V="${{ inputs.otp_version }}"
            echo "with_openssl=${{ inputs.openssl }}" >> $GITHUB_OUTPUT
          fi

          export OTP_VERSION="${OTP_VERSION_V#v}"
          echo "version=${OTP_VERSION}" >> $GITHUB_OUTPUT

          echo "with_wxwidgets=false" >> $GITHUB_OUTPUT
          echo "wxwidgets_version=nil" >> $GITHUB_OUTPUT

          case "${OTP_VERSION}" in
            24.* | 23.*)
              echo "openssl_version=${{ env.DEFAULT_OPENSSL_VERSION_OTP24 }}" >> $GITHUB_OUTPUT
              echo "image=alpine:latest" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "openssl_version=${{ env.DEFAULT_OPENSSL_VERSION }}" >> $GITHUB_OUTPUT
              echo "image=alpine:edge" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Checkout
        if: steps.build-check.outputs.build == 'true'
        uses: actions/checkout@v6

      - name: Cache Precompiled OpenSSL
        if: steps.build-check.outputs.build == 'true'
        id: cache-openssl
        uses: actions/cache@v5
        with:
          key: openssl-${{ steps.build-check.outputs.openssl_version }}-${{ matrix.arch }}-linux-musl
          path: |
            ./openssl-${{ matrix.arch }}-linux-musl.tar.gz

      - name: Download Precompiled OpenSSL
        if: steps.build-check.outputs.build == 'true' && steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          export OPENSSL_FILENAME="openssl-${{ matrix.arch }}-linux-musl.tar.gz"
          curl -fSL "https://github.com/cocoa-xu/openssl-build/releases/download/v${{ steps.build-check.outputs.openssl_version }}/${OPENSSL_FILENAME}" -o "${OPENSSL_FILENAME}"

      - name: Cache OTP Source Code
        if: steps.build-check.outputs.build == 'true'
        id: cache-otp
        uses: actions/cache@v5
        with:
          key: otp-${{ steps.build-check.outputs.version }}
          path: |
            ./otp_src_${{ steps.build-check.outputs.version }}.tar.gz

      - name: Download OTP Source Code
        if: steps.build-check.outputs.build == 'true' && steps.cache-otp.outputs.cache-hit != 'true'
        run: |
          export OTP_VERSION=${{ steps.build-check.outputs.version }}
          curl -fSL "https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz" || \
          curl -fSL "https://github.com/erlang/otp/archive/refs/tags/OTP-${OTP_VERSION}.tar.gz" -o "otp_src_${OTP_VERSION}.tar.gz"

      - name: Pull docker image
        if: steps.build-check.outputs.build == 'true'
        run: |
          sudo docker pull --platform=linux/${{ matrix.arch }} ${{ steps.build-check.outputs.image }}

      - name: Install binfmt
        if: steps.build-check.outputs.build == 'true'
        run: |
          sudo apt update
          sudo apt install -y binfmt-support qemu-user-static

      - name: Precompile
        if: steps.build-check.outputs.build == 'true'
        run: |
          cp .github/script-to-build-musl.sh ./
          cp .github/do-build.sh ./

          bash ./script-to-build-musl.sh \
            "${{ steps.build-check.outputs.version }}" \
            "${{ matrix.arch }}" \
            "${{ steps.build-check.outputs.image }}" \
            "${{ steps.build-check.outputs.with_openssl }}" \
            "${{ steps.build-check.outputs.openssl_version }}" \
            "${{ steps.build-check.outputs.with_wxwidgets }}" \
            "${{ steps.build-check.outputs.wxwidgets_version }}"

      - uses: softprops/action-gh-release@v3
        if: steps.build-check.outputs.build == 'true'
        with:
          tag_name: v${{ steps.build-check.outputs.version }}
          name: v${{ steps.build-check.outputs.version }}
          files: |
            build/*.tar.gz
            build/*.sha256

  deploy-linux-musl:
    runs-on: ubuntu-latest
    needs: linux-musl
    steps:
      - name: deploy by tag
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'cocoa-xu/otp-build'
        env:
          DEPLOY_LINUX_MUSL_HOOK_URL: ${{ secrets.DEPLOY_LINUX_MUSL_HOOK_URL }}
        run: |
          curl -sS --no-progress-meter "${DEPLOY_LINUX_MUSL_HOOK_URL}${{ github.ref_name }}"

      - name: deploy by workflow_dispatch
        if: startsWith(inputs.otp_version, 'v') && github.repository == 'cocoa-xu/otp-build'
        env:
          DEPLOY_LINUX_MUSL_HOOK_URL: ${{ secrets.DEPLOY_LINUX_MUSL_HOOK_URL }}
        run: |
          curl -sS --no-progress-meter "${DEPLOY_LINUX_MUSL_HOOK_URL}${{ inputs.otp_version }}"
